### ISSUE TITLE
Please include python code to compute RGB composites

### ISSUE THREAD

**Issue by whoschek** [ESA-PhiLab/Major-TOM#5]
Please include python code to recompute thumbnails and also how to compute full scale True Color Images from the three RGB bands, perhaps along the lines of https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-2-msi/definitions. In practice, the details of the algorithm matter a great deal.

**Comment by aliFrancis** [comment]
Hi @whoschek . You're right, it should be included somewhere. I'm not sure we want to place it in this Major TOM repo, as it is rather specific to the individual datasets, and may not be the same for future ones, presumably.

I guess the best way is to distribute thumbnail creation functions (and other code/context) alongside the data itself. This could take the form of a simple python file with a set of functions. What do you think?

**Comment by whoschek** [comment]
@aliFrancis Yeah, a simple python file with a set of functions would be great!

For example along the lines of [01-Major-TOM-Filter.ipynb](https://github.com/ESA-PhiLab/Major-TOM/blob/main/01-Major-TOM-Filter.ipynb) or similar.
